version: "3"
services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - $PWD/grafana-storage:/var/lib/grafana
      - $PWD/grafana-datasource.yml:/var/lib/grafana/grafana-datasource.yml
    networks:
      - grafana-prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/prometheus-storage:/prometheus
    networks:
      - grafana-prometheus
#   command: --web.enable-lifecycle --config.file=$PWD/prometheus.yml
  
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - '9100:9100'

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - "./alertmanager.yml:/alertmanager.yml"
#    command:
#      - '--config.file=/alertmanager.yml'
    ports:
      - '9093:9093'

volumes:
  prometheus-storage:
  grafana-storage:

networks:
  grafana-prometheus:
    driver: bridge