version: "3"
services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - $PWD/grafana-storage:/var/lib/grafana
    networks:
      - grafana-prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/prometheus:/prometheus
    networks:
      - grafana-prometheus

networks:
  grafana-prometheus: