global:
  scrape_interval: "10s"
  evaluation_interval: "10s"

rule_files:
  - $PWD/alerts.yml

scrape_configs:
  # Prometheus itself
  # This uses the static method to get metrics endpoints
  - job_name: "prometheus"
    metrics_path: /metrics
    honor_labels: true
    static_configs:
      - targets: ["$HOSTNAME:9090"]
  
  - job_name: "node-exporter"
    metrics_path: /metrics
    honor_labels: true
    static_configs:
      - targets: ["$HOSTNAME:9100"]
        
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets: 
        - '$HOSTNAME:9093'